Revert "[PRMT-2840] Attempt to fix assume-role for ci-agent on gocd."
This reverts commit 98c562ececa4655d5dfd715d434b5abb5058289b.

diff --git a/tasks b/tasks
--- a/tasks
+++ b/tasks
@@ -24,16 +24,13 @@ function assume_ci_role() {
 
 function _get_aws_ssm_secret {
   secret_id=$1
-  echo $secret_id
-  echo "$(aws ssm get-parameters --region "eu-west-2" --name $secret_id --output text)"
-#  json=$(aws ssm get-parameter --region "eu-west-2" --name $secret_id)
-#  if [ $? != 0 ]; then
-#    echo >&2 "Failed to obtain AWS secret from SSM: $secret_id"
-#    exit $EXIT_CODE_GENERAL_FAILURE
-#  fi
-#  echo $json | jq -r ".Parameter.Value"
-
-
+  echo "*** secret id is *** " secret_id
+  json=$(aws ssm get-parameter --with-decryption --region "eu-west-2" --name $secret_id)
+  if [ $? != 0 ]; then
+    echo >&2 "Failed to obtain AWS secret from SSM: $secret_id"
+    exit $EXIT_CODE_GENERAL_FAILURE
+  fi
+  echo $json | jq -r ".Parameter.Value"
 }
 
 function assume_role_for_ci_agent {
