[PRMT-2840] Reverted changes to commit #8bea1ea4
Co-authored-by: ryanbrown-nhs <ryan.brown15@nhs.net>
Co-authored-by: Caius Eugene <caius.eugene1@nhs.net>

diff --git a/tasks b/tasks
--- a/tasks
+++ b/tasks
@@ -38,26 +38,22 @@ function assume_role_for_ci_agent {
   _clear_aws_env_credentials
   session_name="document-store-session"
 
-  ROLE_NAME='Deployer'
+  ROLE_NAME='ci-role'
 
   echo >&2 "Assuming $ROLE_NAME role for CI agent in ${environment} account"
   desired_account_id=$(_get_aws_ssm_secret "/prs/${environment}/user-input/external/aws-account-id")
-  echo "*** desired_account_id is ***" $desired_account_id
   desired_role_arn="arn:aws:iam::$desired_account_id:role/$ROLE_NAME"
 
-  json="$(aws sts assume-role --role-arn "$desired_role_arn" --role-session-name "$session_name")"
+  json="$(aws sts assume-role --role-arn "$desired_role_arn")"
 }
 
-cis2_client_id= echo _get_aws_ssm_secret /development/cis2/client_id
-cis2_client_secret= echo _get_aws_ssm_secret /development/cis2/client_secret
-
 function get_cis2_client_id() {
-  #_get_aws_ssm_secret /development/cis2/client_id
+   #_get_aws_ssm_secret /development/cis2/client_id
   echo "$(aws ssm get-parameters --region ${aws_region} --names /development/cis2/client_id --query Parameters[0].Value --output text)"
 }
 
 function get_cis2_client_secret() {
-  #_get_aws_ssm_secret /development/cis2/client_secret
+   #_get_aws_ssm_secret /development/cis2/client_secret
   echo "$(aws ssm get-parameters --region ${aws_region} --names /development/cis2/client_secret --query Parameters[0].Value --output text)"
 }
 
@@ -123,6 +119,17 @@ function check_env {
   fi
 }
 
+function _get_aws_ssm_secret {
+  secret_id=$1
+  echo "*** secret id is *** " secret_id
+  json=$(aws ssm get-parameter --with-decryption --region "eu-west-2" --name $secret_id)
+  if [ $? != 0 ]; then
+    echo >&2 "Failed to obtain AWS secret from SSM: $secret_id"
+    exit $EXIT_CODE_GENERAL_FAILURE
+  fi
+  echo $json | jq -r ".Parameter.Value"
+}
+
 function _clear_aws_env_credentials {
   unset AWS_ACCESS_KEY_ID
   unset AWS_SECRET_ACCESS_KEY
@@ -145,14 +152,14 @@ function tf_init {
 }
 
 function tf_init_iam() {
-  check_env
-  cd terraform-iam
+    check_env
+    cd terraform-iam
 
-  terraform init -reconfigure \
-    -backend-config key="prs/iam-terraform.tfstate" \
-    -backend-config bucket="prs-${ENVIRONMENT}-terraform-state" \
-    -backend-config dynamodb_table="prs-${ENVIRONMENT}-iam-terraform-state-locking" \
-    -backend-config region="eu-west-2"
+    terraform init -reconfigure \
+            -backend-config key="prs/iam-terraform.tfstate" \
+            -backend-config bucket="prs-${ENVIRONMENT}-terraform-state" \
+            -backend-config dynamodb_table="prs-${ENVIRONMENT}-iam-terraform-state-locking" \
+            -backend-config region=${AWS_DEFAULT_REGION}
 
 }
 
@@ -160,21 +167,21 @@ function tf_iam_plan_func() {
   tf_init_iam
   operation=$1
   terraform get # modules
-  if [[ "${operation}" == "create" ]]; then
-    echo not yet implemented
-    terraform plan -var-file=$ENVIRONMENT.tfvars -out=iam.tfplan
-  elif [[ "${operation}" == "destroy" ]]; then
-    terraform plan -var-file=$ENVIRONMENT.tfvars -out=iam.tfplan -destroy
-  else
-    echo "Unknown operation (should be create or destroy), got: ${operation}"
-    exit 1
-  fi
+    if [[ "${operation}" == "create" ]]; then
+      echo not yet implemented
+    terraform plan -var-file=$ENVIRONMENT.tfvars  -out=iam.tfplan
+    elif [[ "${operation}" == "destroy" ]]; then
+       terraform plan -var-file=$ENVIRONMENT.tfvars -out=iam.tfplan -destroy
+    else
+      echo "Unknown operation (should be create or destroy), got: ${operation}"
+      exit 1
+    fi
 
 }
 
 function tf_iam_apply() {
-  tf_init_iam
-  terraform apply iam.tfplan
+    cd terraform-iam
+    terraform apply iam.tfplan
 }
 
 function tf_plan {
@@ -186,7 +193,7 @@ function tf_plan {
   terraform get # modules
   if [[ "${operation}" == "create" ]]; then
     echo not yet implemented
-    terraform plan -lock=false -var-file=$ENVIRONMENT.tfvars -var lambda_jar_filename=../jars/libs/app.jar -var cognito_cis2_provider_client_id=$(get_cis2_client_id) -var cognito_cis2_provider_client_secret=$(get_cis2_client_secret) -out=tfplan
+    terraform plan -var-file=$ENVIRONMENT.tfvars -var lambda_jar_filename=../app/build/libs/app.jar -out=tfplan -var cognito_cis2_provider_client_id=${cis2_client_id} -var cognito_cis2_provider_client_secret=${cis2_client_secret} -var lambda_jar_filename=../app/build/libs/app.jar -out=tfplan
   elif [[ "${operation}" == "destroy" ]]; then
     terraform plan -var-file="../terraform/${ENVIRONMENT}.tfvars" -var cognito_cis2_provider_client_id=$(get_cis2_client_id) -var cognito_cis2_provider_client_secret=$(get_cis2_client_secret) -var lambda_jar_filename=../app/build/libs/app.jar -out=tfplan -destroy
   else
@@ -225,12 +232,9 @@ build-ui)
   cd build
   tar -czf ../ui.tgz *
   ;;
-build-gradle)
-  ./gradlew app:build
-  ;;
 _tf)
   check_env
-  #tf_init
+  tf_init
   bash
   ;;
 tf)
@@ -239,7 +243,7 @@ tf)
   ;;
 _tf_iam_plan)
   check_env
-  #assume_role_for_ci_agent $ENVIRONMENT
+  assume_role_for_ci_agent $ENVIRONMENT
   tf_iam_plan_func "$2"
   ;;
 tf_iam_plan)
@@ -248,7 +252,7 @@ tf_iam_plan)
   ;;
 _tf_iam_apply)
   check_env
-  #assume_role_for_ci_agent $ENVIRONMENT
+  assume_role_for_ci_agent $ENVIRONMENT
   tf_iam_apply
   ;;
 tf_iam_apply)
@@ -264,7 +268,7 @@ tf_plan)
   dojo -c Dojofile-infra "./tasks _tf_plan $2"
   ;;
 _tf_apply)
-  assume_role_for_ci_agent $ENVIRONMENT
+  _assume_environment_role $ENVIRONMENT
   tf_apply
   ;;
 tf_apply)
