[PRMT-2840] Debugging assume-role for ci-agent.
Co-authored-by: eyupaksu-nhs <eyup.aksu@thoughtworks.com>
Co-authored-by: romanenhs <romane.castera1@nhs.net>

diff --git a/tasks b/tasks
--- a/tasks
+++ b/tasks
@@ -22,6 +22,17 @@ function assume_ci_role() {
   export AWS_SESSION_TOKEN="${sts[2]}"
 }
 
+function _get_aws_ssm_secret {
+  secret_id=$1
+  echo "*** secret id is *** " secret_id
+  json=$(aws ssm get-parameter --with-decryption --region "eu-west-2" --name $secret_id)
+  if [ $? != 0 ]; then
+    echo >&2 "Failed to obtain AWS secret from SSM: $secret_id"
+    exit $EXIT_CODE_GENERAL_FAILURE
+  fi
+  echo $json | jq -r ".Parameter.Value"
+}
+
 function assume_role_for_ci_agent {
   environment=$1
   echo "Environment is $1"
@@ -32,7 +43,7 @@ function assume_role_for_ci_agent {
 
   echo >&2 "Assuming $ROLE_NAME role for CI agent in ${environment} account"
   desired_account_id=$(_get_aws_ssm_secret "/prs/${environment}/user-input/external/aws-account-id")
-  echo "*** desired_account_id is ***" desired_account_id
+  echo "*** desired_account_id is ***" $desired_account_id
   desired_role_arn="arn:aws:iam::$desired_account_id:role/$ROLE_NAME"
 
   json="$(aws sts assume-role --role-arn "$desired_role_arn" --role-session-name "$session_name")"
@@ -111,17 +122,6 @@ function check_env {
     echo "Must set ENVIRONMENT"
     exit 1
   fi
-}
-
-function _get_aws_ssm_secret {
-  secret_id=$1
-  echo "*** secret id is *** " secret_id
-  json=$(aws ssm get-parameter --with-decryption --region "eu-west-2" --name $secret_id)
-  if [ $? != 0 ]; then
-    echo >&2 "Failed to obtain AWS secret from SSM: $secret_id"
-    exit $EXIT_CODE_GENERAL_FAILURE
-  fi
-  echo $json | jq -r ".Parameter.Value"
 }
 
 function _clear_aws_env_credentials {
