[PRMT-3343] Add lambda build to scripts

diff --git a/tasks b/tasks
--- a/tasks
+++ b/tasks
@@ -75,19 +75,12 @@ function get_signout_url {
 function create_ui_config_file() {
   cp ui/src/config.js.example ui/src/config.js
   user_pool="$(jq -r '.cognito_user_pool_ids.value' "$1")"
-  echo "User pool: ${user_pool}" > log.txt
   user_pool_client_id="$(jq -r '.cognito_client_ids.value' "$1")"
-  echo "user_pool_client_id: ${user_pool_client_id}" >> log.txt
   api_endpoint="$(jq -r '.api_gateway_url.value' "$1")"
-  echo "api_endpoint: ${api_endpoint}" >> log.txt
   cognito_domain="$(jq -r '.cognito_user_pool_domain.value' "$1")"
-  echo "cognito_domain: ${cognito_domain}" >> log.txt
   cognito_redirect_signin="$(jq -r '.cognito_redirect_signin.value' "$1")"
-  echo "cognito_redirect_signin: ${cognito_redirect_signin}" >> log.txt
   cognito_redirect_signout="$(jq -r $(get_signout_url) "$1")"
-  echo "cognito_redirect_signout: ${cognito_redirect_signout}" >> log.txt
   amplify_app_id="$(jq -r '.amplify_app_ids.value[0]' "$1")"
-  echo "amplify_app_id: ${amplify_app_id}" >> log.txt
   sed -i "" "s/%pool-id%/${user_pool}/" ui/src/config.js
   sed -i "" "s/%client-id%/${user_pool_client_id}/" ui/src/config.js
   sed -i "" "s/%region%/${aws_region}/" ui/src/config.js
@@ -139,6 +132,7 @@ function run_sandbox() {
       printf "${blue}\nBuilding lambda layers...\n\n${normal}"
       cd ..
       ./gradlew app:build
+      build_lambdas
       ./gradlew app:buildZip
       printf "${blue}\nRefreshing local plan...\n\n${normal}"
       cd ./terraform
@@ -163,10 +157,10 @@ function run_sandbox() {
       printf "${blue}\nBuilding lambda layers...\n\n${normal}"
       cd ..
       ./gradlew app:build
+      build_lambdas
       ./gradlew app:buildZip
       printf "${blue}\nRefreshing local plan...\n\n${normal}"
       cd ./terraform
-      ls ../lambdas/CreateDocumentManifestByNhsNumber/build/libs
       terraform refresh -var-file="dev.tfvars"
       terraform output -json >"../terraform_output.json"
       cd ..
@@ -184,8 +178,18 @@ function run_sandbox() {
     exit 0;
 }
 
+function build_lambdas() {
+    (./gradlew lambdas:CreateDocumentManifestByNhsNumber:build &&
+    ./gradlew lambdas:CreateDocumentReference:build &&
+    ./gradlew lambdas:DeleteDocumentReference:build &&
+    ./gradlew lambdas:DocumentReferenceSearch:build &&
+    ./gradlew lambdas:FakeVirusScannedEvent:build &&
+    ./gradlew lambdas:ReRegistrationEvent:build &&
+    ./gradlew lambdas:SearchPatientDetails:build &&
+    ./gradlew lambdas:VirusScannedEvent:build) || printf "Error building lambdas, ensure you are in root directory."
+}
+
 function deploy_workspace_ui() {
-  printf $3
   app_id="$(jq -r '.amplify_app_ids.value[0]' "$1")"
   aws amplify create-deployment --region "${aws_region}" --app-id "$app_id" --branch-name $3 >deployment.output
   jobId="$(jq -r .jobId deployment.output)"
@@ -194,29 +198,6 @@ function deploy_workspace_ui() {
 
   curl -XPUT --data-binary "@$2" "$zipUploadUrl"
   aws amplify start-deployment --region "${aws_region}" --app-id "$app_id" --branch-name $3 --job-id "${jobId}"
-}
-
-function create_workspace_ui_config_file() {
-  cp ui/src/config.js.example ui/src/config.js
-  api_endpoint="$(jq -r '.api_gateway_url.value' "$1")"
-  amplify_app_id="$(jq -r '.amplify_app_ids.value[0]' "$1")"
-  sed -i "" "s/%region%/${aws_region}/" ui/src/config.js
-  sed -i "" "s~%api-endpoint%~${api_endpoint}~" ui/src/config.js
-  sed -i "" "s/%amplify-app-id%/${amplify_app_id}/" ui/src/config.js
-  sed -i "" "s/%oidc-provider-id%/$OIDC_PROVIDER_ID/" ui/src/config.js
-}
-
-function get_terraform_output() {
-  tf_init
-  terraform output -json >"../$1"
-  cd ..
-}
-
-function check_env {
-  if [[ -z "${ENVIRONMENT}" ]]; then
-    echo "Must set ENVIRONMENT"
-    exit 1
-  fi
 }
 
 function tf_init {
@@ -250,23 +231,48 @@ function confirm_current_role {
   fi
 }
 
+function check_env {
+  if [[ -z "${ENVIRONMENT}" ]]; then
+    echo "Must set ENVIRONMENT"
+    exit 1
+  fi
+}
+
+
 function get_user_pool_id {
   echo "$(aws cognito-idp list-user-pools --region ${aws_region} --query 'UserPools[?Name==`doc-store-user-pool`].Id' --max-results 1 | jq -r '.[0]')"
+}
+
+function get_terraform_output() {
+  tf_init
+  terraform output -json >"../$1"
+  cd ..
 }
 
 function create_cognito_user {
   aws cognito-idp admin-create-user --user-pool-id $(get_user_pool_id) --username "$1" --temporary-password "$2"
 }
 
+function create_json_for_nhs_api_public_key() {
+  echo $(get_ssm_parameter /prs/${ENVIRONMENT}/user-input/pds-fhir-public-key) >ui/public/jwks.json
+}
+
+function create_workspace_ui_config_file() {
+  cp ui/src/config.js.example ui/src/config.js
+  api_endpoint="$(jq -r '.api_gateway_url.value' "$1")"
+  amplify_app_id="$(jq -r '.amplify_app_ids.value[0]' "$1")"
+  sed -i "" "s/%region%/${aws_region}/" ui/src/config.js
+  sed -i "" "s~%api-endpoint%~${api_endpoint}~" ui/src/config.js
+  sed -i "" "s/%amplify-app-id%/${amplify_app_id}/" ui/src/config.js
+  sed -i "" "s/%oidc-provider-id%/$OIDC_PROVIDER_ID/" ui/src/config.js
+}
+
+
 function delete_cognito_user {
   aws cognito-idp admin-delete-user --user-pool-id $(get_user_pool_id) --username "$1"
   if [[ $? -eq 0 ]]; then
     echo "User deleted"
   fi
-}
-
-function create_json_for_nhs_api_public_key() {
-  echo $(get_ssm_parameter /prs/${ENVIRONMENT}/user-input/pds-fhir-public-key) >ui/public/jwks.json
 }
 
 readonly command="$1"
